name = "nunchaku"
version = "0.1.0"
defaultTargets = ["Nunchaku"]
testRunner = "Test"

[[lean_lib]]
name = "Test"
leanOptions = { experimental.module = true }

[[lean_lib]]
name = "Nunchaku"
leanOptions = { experimental.module = true }
precompileModules = true
