name = "chako"
version = "0.1.0"
defaultTargets = ["Chako"]
testRunner = "Test"

[[lean_lib]]
name = "Test"
leanOptions = { experimental.module = true }

[[lean_lib]]
name = "Chako"
leanOptions = { experimental.module = true }
precompileModules = true
